#!/usr/bin/env python3
"""Profile rv32i_core waveforms and report basic pipeline stats.

The script reads the VCD generated by the Verilator core testbench. If a
program hex file is provided, retired PCs are decoded back to instruction
words so idle spin loops can be separated from useful benchmark work.
"""

from __future__ import annotations

import argparse
import json
import math
import re
import sys
from collections import Counter, defaultdict, deque
from dataclasses import dataclass, field
from pathlib import Path
from typing import Deque, Dict, Iterable, Iterator, List, Optional, Tuple


VAR_RE = re.compile(r"^\s*\$var\s+\S+\s+(\d+)\s+(\S+)\s+(.+?)\s+\$end\s*$")
SCOPE_RE = re.compile(r"^\s*\$scope\s+\S+\s+(\S+)\s+\$end\s*$")
UPSCOPE_RE = re.compile(r"^\s*\$upscope\s+\$end\s*$")
TIMESCALE_RE = re.compile(r"^\s*\$timescale\s+(.+?)\s+\$end\s*$")
VECTOR_RE = re.compile(r"^[bBrR]([^\s]+)\s+(\S+)$")
SCALAR_RE = re.compile(r"^([01xXzZ])(\S+)$")


@dataclass
class VcdHeader:
    code_to_paths: Dict[str, List[str]] = field(default_factory=lambda: defaultdict(list))
    widths: Dict[str, int] = field(default_factory=dict)
    timescale: Optional[str] = None


@dataclass
class CoreSample:
    cycle: int
    time: int
    current_pc: Optional[int]
    inst: Optional[int]
    if_id_q: Optional[int]
    if_id_width: int
    id_ex_q: Optional[int]
    id_ex_width: int
    ex_mem_q: Optional[int]
    ex_mem_width: int
    mem_wb_q: Optional[int]
    mem_wb_width: int
    load_use_hazard: bool
    pc_sel: bool
    pc_en: bool
    if_id_en: bool
    if_id_flush: bool
    id_ex_flush: bool
    reg_write_en: bool
    mem_write_en: bool


@dataclass
class RetiredInstruction:
    cycle: int
    pc: Optional[int]
    inst: Optional[int]
    inst_class: str
    idle_spin: bool


def parse_int_bits(bits: str) -> Optional[int]:
    if any(ch in bits for ch in "xXzZ"):
        return None
    return int(bits, 2)


def strip_vcd_range(name: str) -> str:
    parts = name.split()
    if len(parts) > 1 and re.fullmatch(r"\[[^]]+\]", parts[-1]):
        parts = parts[:-1]
    return " ".join(parts)


def parse_header(lines: Iterable[str]) -> Tuple[VcdHeader, Iterator[str]]:
    header = VcdHeader()
    scopes: List[str] = []
    iterator = iter(lines)

    for line in iterator:
        timescale_match = TIMESCALE_RE.match(line)
        if timescale_match:
            header.timescale = timescale_match.group(1)
            continue

        scope_match = SCOPE_RE.match(line)
        if scope_match:
            scopes.append(scope_match.group(1))
            continue

        if UPSCOPE_RE.match(line):
            if scopes:
                scopes.pop()
            continue

        var_match = VAR_RE.match(line)
        if var_match:
            width = int(var_match.group(1))
            code = var_match.group(2)
            name = strip_vcd_range(var_match.group(3))
            path = ".".join(scopes + [name])
            header.code_to_paths[code].append(path)
            header.widths[path] = width
            continue

        if line.strip() == "$enddefinitions $end":
            return header, iterator

    raise ValueError("VCD header ended before $enddefinitions")


def parse_change(line: str) -> Optional[Tuple[str, Optional[int]]]:
    text = line.strip()
    if not text or text.startswith("$"):
        return None

    vector_match = VECTOR_RE.match(text)
    if vector_match:
        return vector_match.group(2), parse_int_bits(vector_match.group(1))

    scalar_match = SCALAR_RE.match(text)
    if scalar_match:
        value = scalar_match.group(1)
        return scalar_match.group(2), None if value in "xXzZ" else int(value)

    return None


def find_signal(header: VcdHeader, wanted_path: str) -> str:
    if wanted_path in header.widths:
        return wanted_path

    suffix = "." + wanted_path
    matches = [path for path in header.widths if path.endswith(suffix)]
    if len(matches) == 1:
        return matches[0]
    if matches:
        matches.sort(key=len)
        return matches[0]
    raise KeyError(f"missing VCD signal: {wanted_path}")


def get_signal(
    state: Dict[str, Optional[int]],
    paths: Dict[str, str],
    name: str,
    default: Optional[int] = None,
) -> Optional[int]:
    return state.get(paths[name], default)


def value_as_bool(value: Optional[int]) -> bool:
    return bool(value) if value is not None else False


def msb_field(value: Optional[int], width: int, offset: int, size: int) -> Optional[int]:
    if value is None or width < offset + size:
        return None
    shift = width - offset - size
    mask = (1 << size) - 1
    return (value >> shift) & mask


def pipeline_valid(value: Optional[int], width: int) -> bool:
    return value_as_bool(msb_field(value, width, 0, 1))


def pipeline_pc(value: Optional[int], width: int) -> Optional[int]:
    return msb_field(value, width, 1, 32)


def mem_wb_pc_plus_4(value: Optional[int], width: int) -> Optional[int]:
    return msb_field(value, width, 1, 32)


def load_program_hex(path: Path) -> Dict[int, int]:
    memory: Dict[int, int] = {}
    word_addr = 0

    with path.open("r", encoding="utf-8") as file:
        for raw_line in file:
            line = raw_line.split("//", 1)[0].split("#", 1)[0].strip()
            if not line:
                continue
            for token in line.split():
                if token.startswith("@"):
                    word_addr = int(token[1:], 16)
                    continue
                memory[word_addr * 4] = int(token.replace("_", ""), 16)
                word_addr += 1

    return memory


def sign_extend(value: int, bits: int) -> int:
    sign_bit = 1 << (bits - 1)
    return (value ^ sign_bit) - sign_bit


def jal_imm(inst: int) -> int:
    imm = ((inst >> 31) & 0x1) << 20
    imm |= ((inst >> 12) & 0xff) << 12
    imm |= ((inst >> 20) & 0x1) << 11
    imm |= ((inst >> 21) & 0x3ff) << 1
    return sign_extend(imm, 21)


def branch_imm(inst: int) -> int:
    imm = ((inst >> 31) & 0x1) << 12
    imm |= ((inst >> 7) & 0x1) << 11
    imm |= ((inst >> 25) & 0x3f) << 5
    imm |= ((inst >> 8) & 0xf) << 1
    return sign_extend(imm, 13)


def inst_class(inst: Optional[int]) -> str:
    if inst is None:
        return "unknown"

    opcode = inst & 0x7f
    return {
        0b0110011: "alu_reg",
        0b0010011: "alu_imm",
        0b0000011: "load",
        0b0100011: "store",
        0b1100011: "branch",
        0b1101111: "jal",
        0b1100111: "jalr",
        0b0110111: "lui",
        0b0010111: "auipc",
        0b1110011: "system",
    }.get(opcode, "unknown")


def is_idle_spin(inst: Optional[int], pc: Optional[int], idle_pcs: set[int]) -> bool:
    if pc is not None and pc in idle_pcs:
        return True
    if inst is None:
        return False

    opcode = inst & 0x7f
    rd = (inst >> 7) & 0x1f
    rs1 = (inst >> 15) & 0x1f
    rs2 = (inst >> 20) & 0x1f
    funct3 = (inst >> 12) & 0x7

    if opcode == 0b1101111 and rd == 0 and jal_imm(inst) == 0:
        return True
    if opcode == 0b1100011 and funct3 == 0 and rs1 == 0 and rs2 == 0 and branch_imm(inst) == 0:
        return True
    return False


def iter_samples(vcd_path: Path) -> Iterator[CoreSample]:
    with vcd_path.open("r", encoding="utf-8") as file:
        header, body = parse_header(file)
        signal_names = {
            "clk": "TOP.clk_i",
            "rst_ni": "TOP.rst_ni",
            "current_pc": "TOP.rv32i_core.current_pc",
            "inst": "TOP.rv32i_core.inst",
            "if_id_q": "TOP.rv32i_core.if_id_q",
            "id_ex_q": "TOP.rv32i_core.id_ex_q",
            "ex_mem_q": "TOP.rv32i_core.ex_mem_q",
            "mem_wb_q": "TOP.rv32i_core.mem_wb_q",
            "load_use_hazard": "TOP.rv32i_core.load_use_hazard",
            "pc_sel": "TOP.rv32i_core.pc_sel",
            "pc_en": "TOP.rv32i_core.pc_en",
            "if_id_en": "TOP.rv32i_core.if_id_en",
            "if_id_flush": "TOP.rv32i_core.if_id_flush",
            "id_ex_flush": "TOP.rv32i_core.id_ex_flush",
            "reg_write_en": "TOP.rv32i_core.reg_write_en",
            "mem_write_en": "TOP.rv32i_core.mem_write_en",
        }
        paths = {key: find_signal(header, path) for key, path in signal_names.items()}
        state: Dict[str, Optional[int]] = {}
        time = 0
        pending: List[Tuple[str, Optional[int]]] = []
        cycle = 0

        def flush_pending() -> Optional[CoreSample]:
            nonlocal cycle
            if not pending:
                return None

            old_clk = state.get(paths["clk"])
            for code, value in pending:
                for path in header.code_to_paths.get(code, []):
                    state[path] = value
            pending.clear()

            new_clk = state.get(paths["clk"])
            if old_clk == 0 and new_clk == 1 and value_as_bool(state.get(paths["rst_ni"])):
                sample = CoreSample(
                    cycle=cycle,
                    time=time,
                    current_pc=get_signal(state, paths, "current_pc"),
                    inst=get_signal(state, paths, "inst"),
                    if_id_q=get_signal(state, paths, "if_id_q"),
                    if_id_width=header.widths[paths["if_id_q"]],
                    id_ex_q=get_signal(state, paths, "id_ex_q"),
                    id_ex_width=header.widths[paths["id_ex_q"]],
                    ex_mem_q=get_signal(state, paths, "ex_mem_q"),
                    ex_mem_width=header.widths[paths["ex_mem_q"]],
                    mem_wb_q=get_signal(state, paths, "mem_wb_q"),
                    mem_wb_width=header.widths[paths["mem_wb_q"]],
                    load_use_hazard=value_as_bool(get_signal(state, paths, "load_use_hazard", 0)),
                    pc_sel=value_as_bool(get_signal(state, paths, "pc_sel", 0)),
                    pc_en=value_as_bool(get_signal(state, paths, "pc_en", 1)),
                    if_id_en=value_as_bool(get_signal(state, paths, "if_id_en", 1)),
                    if_id_flush=value_as_bool(get_signal(state, paths, "if_id_flush", 0)),
                    id_ex_flush=value_as_bool(get_signal(state, paths, "id_ex_flush", 0)),
                    reg_write_en=value_as_bool(get_signal(state, paths, "reg_write_en", 0)),
                    mem_write_en=value_as_bool(get_signal(state, paths, "mem_write_en", 0)),
                )
                cycle += 1
                return sample
            return None

        for raw_line in body:
            line = raw_line.strip()
            if not line:
                continue
            if line.startswith("#"):
                sample = flush_pending()
                if sample is not None:
                    yield sample
                time = int(line[1:])
                continue

            change = parse_change(line)
            if change is not None:
                pending.append(change)

        sample = flush_pending()
        if sample is not None:
            yield sample


def ratio(numerator: float, denominator: float) -> Optional[float]:
    if denominator == 0:
        return None
    return numerator / denominator


def finite_or_none(value: Optional[float]) -> Optional[float]:
    if value is None or not math.isfinite(value):
        return None
    return value


def round_or_none(value: Optional[float], digits: int = 4) -> Optional[float]:
    value = finite_or_none(value)
    return round(value, digits) if value is not None else None


def profile_vcd(
    vcd_path: Path,
    program: Optional[Dict[int, int]],
    idle_pcs: set[int],
    clock_mhz: Optional[float],
) -> Dict[str, object]:
    samples = list(iter_samples(vcd_path))
    retired: List[RetiredInstruction] = []
    stage_occupancy = Counter()
    events = Counter()
    inst_classes = Counter()
    issue_by_pc: Dict[int, Deque[int]] = defaultdict(deque)
    latencies: List[int] = []
    first_idle_cycle: Optional[int] = None
    last_useful_retire_cycle: Optional[int] = None
    pc_changes = 0
    previous_pc: Optional[int] = None

    for sample in samples:
        if previous_pc is not None and sample.current_pc is not None and sample.current_pc != previous_pc:
            pc_changes += 1
        previous_pc = sample.current_pc

        if pipeline_valid(sample.if_id_q, sample.if_id_width):
            stage_occupancy["if_id"] += 1
        if pipeline_valid(sample.id_ex_q, sample.id_ex_width):
            stage_occupancy["id_ex"] += 1
            issue_pc = pipeline_pc(sample.id_ex_q, sample.id_ex_width)
            if issue_pc is not None:
                issue_by_pc[issue_pc].append(sample.cycle)
        if pipeline_valid(sample.ex_mem_q, sample.ex_mem_width):
            stage_occupancy["ex_mem"] += 1
        if pipeline_valid(sample.mem_wb_q, sample.mem_wb_width):
            stage_occupancy["mem_wb"] += 1

        events["load_use_stall_cycles"] += int(sample.load_use_hazard)
        events["taken_branch_cycles"] += int(sample.pc_sel)
        events["pc_hold_cycles"] += int(not sample.pc_en)
        events["if_id_hold_cycles"] += int(not sample.if_id_en)
        events["if_id_flush_cycles"] += int(sample.if_id_flush)
        events["id_ex_flush_cycles"] += int(sample.id_ex_flush)
        events["reg_write_cycles"] += int(sample.reg_write_en)
        events["mem_write_cycles"] += int(sample.mem_write_en)

        if pipeline_valid(sample.mem_wb_q, sample.mem_wb_width):
            pc_plus_4 = mem_wb_pc_plus_4(sample.mem_wb_q, sample.mem_wb_width)
            retired_pc = None if pc_plus_4 is None else (pc_plus_4 - 4) & 0xFFFFFFFF
            inst = program.get(retired_pc) if program is not None and retired_pc is not None else None
            kind = inst_class(inst)
            idle = is_idle_spin(inst, retired_pc, idle_pcs)
            retired.append(
                RetiredInstruction(
                    cycle=sample.cycle,
                    pc=retired_pc,
                    inst=inst,
                    inst_class=kind,
                    idle_spin=idle,
                )
            )
            inst_classes[kind] += 1

            if idle and first_idle_cycle is None:
                first_idle_cycle = sample.cycle
            if not idle:
                last_useful_retire_cycle = sample.cycle

            if retired_pc is not None and issue_by_pc[retired_pc]:
                issue_cycle = issue_by_pc[retired_pc].popleft()
                latencies.append(sample.cycle - issue_cycle + 1)

    total_cycles = len(samples)
    all_retired = len(retired)
    idle_retired = sum(1 for item in retired if item.idle_spin)
    useful_retired = all_retired - idle_retired
    useful_window_cycles = None
    if last_useful_retire_cycle is not None:
        useful_window_cycles = last_useful_retire_cycle + 1

    ipc = ratio(all_retired, total_cycles)
    cpi = ratio(total_cycles, all_retired)
    useful_ipc = ratio(useful_retired, useful_window_cycles or 0)
    useful_cpi = ratio(useful_window_cycles or 0, useful_retired)
    clock_hz = None if clock_mhz is None else clock_mhz * 1_000_000.0

    report: Dict[str, object] = {
        "vcd": str(vcd_path),
        "cycles_after_reset": total_cycles,
        "pc_changes": pc_changes,
        "retired_instructions": all_retired,
        "useful_retired_instructions": useful_retired,
        "idle_spin_retired_instructions": idle_retired,
        "first_idle_retire_cycle": first_idle_cycle,
        "last_useful_retire_cycle": last_useful_retire_cycle,
        "useful_window_cycles": useful_window_cycles,
        "ipc": round_or_none(ipc),
        "cpi": round_or_none(cpi),
        "useful_ipc": round_or_none(useful_ipc),
        "useful_cpi": round_or_none(useful_cpi),
        "throughput_instructions_per_cycle": round_or_none(ipc),
        "throughput_useful_instructions_per_cycle": round_or_none(useful_ipc),
        "estimated_throughput_instructions_per_second": round_or_none(ipc * clock_hz, 2) if ipc and clock_hz else None,
        "estimated_useful_instructions_per_second": round_or_none(useful_ipc * clock_hz, 2) if useful_ipc and clock_hz else None,
        "stage_occupancy_cycles": dict(stage_occupancy),
        "events": dict(events),
        "retired_instruction_classes": dict(inst_classes),
        "issue_to_retire_latency_cycles": {
            "samples": len(latencies),
            "min": min(latencies) if latencies else None,
            "max": max(latencies) if latencies else None,
            "avg": round_or_none(sum(latencies) / len(latencies)) if latencies else None,
        },
        "retired_trace": [
            {
                "cycle": item.cycle,
                "pc": None if item.pc is None else f"0x{item.pc:08x}",
                "inst": None if item.inst is None else f"0x{item.inst:08x}",
                "class": item.inst_class,
                "idle_spin": item.idle_spin,
            }
            for item in retired
        ],
    }
    return report


def format_rate(value: Optional[object]) -> str:
    if value is None:
        return "n/a"
    if isinstance(value, float):
        return f"{value:g}"
    return str(value)


def print_report(report: Dict[str, object], show_trace: bool) -> None:
    print(f"Core profile: {report['vcd']}")
    print(f"  cycles after reset: {report['cycles_after_reset']}")
    print(
        "  retired instructions: "
        f"{report['retired_instructions']} total, "
        f"{report['useful_retired_instructions']} useful, "
        f"{report['idle_spin_retired_instructions']} idle spin"
    )
    print(f"  CPI / IPC: {format_rate(report['cpi'])} / {format_rate(report['ipc'])}")
    print(f"  useful CPI / IPC: {format_rate(report['useful_cpi'])} / {format_rate(report['useful_ipc'])}")

    est_ips = report.get("estimated_throughput_instructions_per_second")
    est_useful_ips = report.get("estimated_useful_instructions_per_second")
    if est_ips is not None or est_useful_ips is not None:
        print(f"  estimated throughput: {format_rate(est_ips)} instr/s total, {format_rate(est_useful_ips)} useful instr/s before idle")

    latency = report["issue_to_retire_latency_cycles"]
    assert isinstance(latency, dict)
    print(
        "  issue-to-retire latency cycles: "
        f"avg={format_rate(latency['avg'])}, "
        f"min={format_rate(latency['min'])}, "
        f"max={format_rate(latency['max'])}, "
        f"samples={latency['samples']}"
    )

    events = report["events"]
    assert isinstance(events, dict)
    print(
        "  events: "
        f"load stalls={events.get('load_use_stall_cycles', 0)}, "
        f"taken branches={events.get('taken_branch_cycles', 0)}, "
        f"mem writes={events.get('mem_write_cycles', 0)}, "
        f"reg writes={events.get('reg_write_cycles', 0)}"
    )

    stage_occupancy = report["stage_occupancy_cycles"]
    assert isinstance(stage_occupancy, dict)
    print(
        "  stage occupancy cycles: "
        f"IF/ID={stage_occupancy.get('if_id', 0)}, "
        f"ID/EX={stage_occupancy.get('id_ex', 0)}, "
        f"EX/MEM={stage_occupancy.get('ex_mem', 0)}, "
        f"MEM/WB={stage_occupancy.get('mem_wb', 0)}"
    )

    classes = report["retired_instruction_classes"]
    assert isinstance(classes, dict)
    if classes:
        class_text = ", ".join(f"{name}={count}" for name, count in sorted(classes.items()))
        print(f"  retired classes: {class_text}")

    if show_trace:
        trace = report["retired_trace"]
        assert isinstance(trace, list)
        print("  retired trace:")
        for item in trace:
            print(
                f"    cycle={item['cycle']:>4} "
                f"pc={item['pc'] or 'unknown'} "
                f"inst={item['inst'] or 'unknown'} "
                f"class={item['class']} "
                f"idle={item['idle_spin']}"
            )


def parse_idle_pc(values: Iterable[str]) -> set[int]:
    pcs: set[int] = set()
    for value in values:
        pcs.add(int(value, 0))
    return pcs


def build_arg_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Report rv32i_core CPI, IPC, latency, stall, and retire stats from a VCD.")
    parser.add_argument("--vcd", default="waves/rv32i_core.vcd", type=Path, help="VCD waveform to profile.")
    parser.add_argument("--program", type=Path, help="Verilog hex program loaded into instruction memory.")
    parser.add_argument("--idle-pc", action="append", default=[], help="PC to treat as idle/spin code. Accepts decimal or 0x hex.")
    parser.add_argument("--clock-mhz", type=float, help="Optional target clock in MHz for instr/s estimates.")
    parser.add_argument("--json", action="store_true", help="Print full JSON instead of the human report.")
    parser.add_argument("--trace", action="store_true", help="Include the retired-instruction trace in the human report.")
    return parser


def main(argv: Optional[List[str]] = None) -> int:
    parser = build_arg_parser()
    args = parser.parse_args(argv)

    if not args.vcd.exists():
        parser.error(f"VCD does not exist: {args.vcd}")

    program = None
    if args.program is not None:
        if not args.program.exists():
            parser.error(f"program hex does not exist: {args.program}")
        program = load_program_hex(args.program)

    try:
        report = profile_vcd(args.vcd, program, parse_idle_pc(args.idle_pc), args.clock_mhz)
    except (KeyError, ValueError) as exc:
        print(f"profile_core.py: {exc}", file=sys.stderr)
        return 1

    if args.json:
        print(json.dumps(report, indent=2, sort_keys=True))
    else:
        print_report(report, show_trace=args.trace)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
